spring:
  application:
    name: eureka-client

server:
  port: 30001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/
  instance:
#    每个5秒钟，向注册中心发送一条续约指令
    lease-renewal-interval-in-seconds: 5
#    如歌30秒内，仍然没有收到服务续约请求，判定服务过期
    lease-expiration-duration-in-seconds: 30
